### ISSUE TITLE
The Lullabot isn't charging

### ISSUE THREAD

**Issue by ericduran** [Lullabot/lullabot-site-offline#1]
it seems like the Lullabot is stuck in it's current state.

It has been charging for a while yet the battery indicator is still at the same level. I'm worry it's broken.

As a user I would expect the batteries to grow as the Lullabot is charging.

Please fix.

kthxbai

**Comment by ericduran** [comment]
:+1:

**Comment by deviantintegral** [comment]
Pull requests accepted.

**Comment by blakehall** [comment]
:poop:

**Comment by eaton** [comment]
As a user, I want to see moving images.

**Comment by blakehall** [comment]
:dancers:

**Comment by davereid** [comment]
:scream_cat:

**Comment by brockboland** [comment]
![hungryclap](https://f.cloud.github.com/assets/163838/365660/938142f0-a254-11e2-8f57-809fa2be7b2d.gif)

**Comment by sirkitree** [comment]
fixed :ship:

**Comment by davereid** [comment]
![](http://assets0.ordienetworks.com/images/GifGuide/friday/tumblr_li2qyapSUr1qbg3ylo1_400.gif)

**Comment by ericduran** [comment]
Awesome thanks.

**Comment by justafish** [comment]
![1339827139931](https://f.cloud.github.com/assets/345613/365686/5fbbd010-a255-11e2-9cbe-e0081d321859.jpg)

**Comment by davereid** [comment]
![](https://twimg0-a.akamaihd.net/profile_images/3051583218/c6cfcf78c9e526b0110d7039d274ad3f.png)

**Comment by blakehall** [comment]
:sunglasses:

**Comment by msonnabaum** [comment]
![](http://i.qkme.me/3tuh64.jpg)
